### ISSUE TITLE
I uploaded my mdb file but this tool doesn't generate an output

### ISSUE THREAD

**Issue by aoelvp94** [OSTnm/tiny_mdb#2]
W10
I uploaded my mdb file but this tool doesn't generate an output.
[db.zip](https://github.com/OSTnm/tiny_mdb/files/4271156/db.zip)

**Comment by aoelvp94** [comment]
I ran this with Ubuntu and I can see that the problem is about filtering of columns and keys, can it be? Is this tool generic? Ty!

**Comment by OSTnm** [comment]
no, it is not generic but for the dedicated project.
1. only support 1 table.
2. hardcode "summary" generation.
and I have no plan to develop it recently.
